//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet5
{
    using System;
    using System.Collections.Generic;
    
    public partial class competud
    {
        public int CompEtud_CompetenceId { get; set; }
        public int CompEtud_EtudiantId { get; set; }
        public int CompEtud_Etat { get; set; }
    
        public virtual competence competence { get; set; }
        public virtual etudiant etudiant { get; set; }
    }
}
